In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("advancedLinAlg.ipynb")

## Lecture Section

In this lecture, we will cover more linear algebra.
We will cover:
* Basis
    * Change of Basis
* Rank & Determinants
* Eigenvectors & Eigenvalues
* Positive Definite Matrices

In [4]:
import numpy as np
from numpy import linalg as la

## Basis

A basis is a linearly independent set of vectors that belong to a vector space. The basis vectors can be used as linear combinations to create all other vectors in the vector space, but they are linearly independent of themselves.

For example:

In [3]:
np.array([[1], [0]])
np.array([[0], [1]])

array([[0],
       [1]])

These two vectors are the standard basis of **R2**. (They are the *standard* because they correspond to the axes of the plane.)

Another example of basis vectors for **R2** are:

In [5]:
print(np.array([[1], [0]]))
print(np.array([[1], [-1]]))

[[1]
 [0]]
[[ 1]
 [-1]]


Or:

In [6]:
b1 = np.array([[0], [1]])
b2 = np.array([[1], [1]])
print("b1:", b1)
print("b2:", b2)

b1: [[0]
 [1]]
b2: [[1]
 [1]]


We can get a vector from the sample space by using that vector's coordinate vector with the basis. For example, we could have the vector

```python
s = 3*b1 + 1*b2
```

In [7]:
s = 3*b1 + 1*b2
s

array([[1],
       [4]])

This vector's coordinate vector is:

In [8]:
np.array([[3], [1]])

array([[3],
       [1]])

## Change of Basis

What if we wanted that vector s, from above, but using a different set of basis, such as:

In [9]:
print(np.array([[1], [0]]))
print(np.array([[1], [-1]]))
# OR
print(np.array([[1], [0]]))
print(np.array([[0], [1]]))

[[1]
 [0]]
[[ 1]
 [-1]]
[[1]
 [0]]
[[0]
 [1]]


To do this, we need to do a *change of basis*.

Let's do an example. Let's move from this basis:

In [10]:
b1 = np.array([[1], [0]])
b2 = np.array([[1], [-1]])
print("b1:", b1)
print("b2:", b2)

b1: [[1]
 [0]]
b2: [[ 1]
 [-1]]


to this basis:

In [11]:
c1 = np.array([[0], [1]])
c2 = np.array([[1], [1]])
print("c1:", c1)
print("c2:", c2)

c1: [[0]
 [1]]
c2: [[1]
 [1]]


First, we need to represent the first basis in terms of the second.

```
b1 = -c1 + c2
b2 = -2*c1 + c2
```

We can verify this:

In [12]:
print((-1)*c1 + c2)
print((-2)*c1 + c2)

[[1]
 [0]]
[[ 1]
 [-1]]


The coordinate vectors of these equations are:

In [13]:
b1c = np.array([[-1], [1]])
b2c = np.array([[-2], [1]])
print("b1c:", b1c)
print("b2c:", b2c)

b1c: [[-1]
 [ 1]]
b2c: [[-2]
 [ 1]]


To switch from basis b to basis c, the change-of-basis matrix is:

In [14]:
# R fills column-wise, so columns are [-1,1] and [-2,1]
P = np.array([[-1, -2], [1, 1]])
P

array([[-1, -2],
       [ 1,  1]])

Then, we need to multiply it by our original vector's coordinates. Let's use (1, 1) in basis b as an example. In basis B, (1, 1) has the coordinates (2, -1).

In [15]:
P @ np.array([[2], [-1]])

array([[0],
       [1]])

This gives us our coordinate vector for the second set of basis. We can double check:

In [16]:
# first basis
b1 = np.array([[1], [0]])
b2 = np.array([[1], [-1]])
print("2*b1 + (-1)*b2 =", (2)*b1 + (-1)*b2)

c1 = np.array([[0], [1]])
c2 = np.array([[1], [1]])
print("0*c1 + 1*c2 =", (0)*c1 + (1)*c2)

2*b1 + (-1)*b2 = [[1]
 [1]]
0*c1 + 1*c2 = [[1]
 [1]]


In Python we can do this like so, using our s from before. This time, we are multiplying with the actual vector we have, and taking the inverse of the change-of-basis matrix. It will get us the same answer.

In [17]:
# define the original basis
b1 = np.array([0, 1])
b2 = np.array([1, 1])
B = np.column_stack((b1, b2))
print("B:\n", B)

# take the vector that we care about (1,4)
v = np.array([1, 4])

# define a new basis (e.g., standard basis)
B_new = np.column_stack((np.array([0, 1]), np.array([1, 0])))

# Coordinates of v in the new basis
v_in_new_basis = la.inv(B_new) @ v
print("v in new basis:", v_in_new_basis)

# check that we still get (1, 4)
print(4*np.array([[0], [1]]) + 1*np.array([[1], [0]]))
print(3*b1.reshape(-1,1) + 1*b2.reshape(-1,1))

B:
 [[0 1]
 [1 1]]
v in new basis: [4. 1.]
[[1]
 [4]]
[[1]
 [4]]


Both methods will get you the correct answer!

** Taking the inverse maps the standard basis back to B-coordinates, that's why this works! You can think of this as solving Ax = b, where the new basis makes up the column vectors of A, and b is the coefficients in the new basis.

Proving that with (1, 1), from above:

In [18]:
# define the original basis
b1 = np.array([[1], [0]])
b2 = np.array([[1], [-1]])

# take the vector that we care about (1,1)
v = np.array([1, 1])

# define a new basis
B_new = np.column_stack((np.array([0, 1]), np.array([1, 1])))

# Coordinates of v in the new basis
v_in_new_basis = la.inv(B_new) @ v
print("v in new basis:", v_in_new_basis)

# check that we still get (1, 1)
print(2*b1 + (-1)*b2)
print(0*np.array([[0], [1]]) + 1*np.array([[1], [1]]))

v in new basis: [0. 1.]
[[1]
 [1]]
[[1]
 [1]]


## Rank & Determinants

Like we learned before, rank is the number of linearly independent row vectors. A nxn matrix is full rank if its rank is also n.
If we are solving a system of equations:


A @ x = b


and A is full rank, it has one unique solution. If it is not full rank, it either has infinitely many or no solution.

We can use the determinant to find the same thing. If the determinant is 0, then A is not full rank.

In [19]:
# solve
# 3x + 2y - 4z = 2
# x - 2y + 2z = 4
# -5x + y + z = 12

A = np.column_stack(([3,1,-5], [2,-2,1], [-4,2,1]))
rank_A = la.matrix_rank(A)
det_A = la.det(A)
print("rank_A:", rank_A)   # n = 3, full rank
print("det_A:", det_A)     # not 0, full rank

rank_A: 3
det_A: 1.999999999999999


## Eigenvectors & Eigenvalues

Switching gears...

If you've never heard of eigenvectors or eigenvalues before, don't worry.

Eigenvectors are special vectors that remain in the same direction after a linear transformation, and the eigenvalue is how much the corresponding eigenvector stretched or compressed during that transformation.

For a square matrix A, we have an eigenvector (x) and an eigenvalue (lambda) if:


Ax = lambda * x


The determinant is the product of the eigenvalues.

In [20]:
eigenvalues, eigenvectors = la.eig(A)
print("Eigenvectors:\n", eigenvectors)
print("Eigenvalues:", eigenvalues)

Eigenvectors:
 [[-0.73159441 -0.27788789 -0.48449936]
 [ 0.07336297 -0.75680236  0.66528096]
 [ 0.6777813  -0.59163208 -0.56803311]]
Eigenvalues: [ 6.50521983 -0.06930828 -4.43591155]


In [21]:
print("det(A):", la.det(A))
print("Product of eigenvalues:", np.prod(eigenvalues))

det(A): 1.999999999999999
Product of eigenvalues: 1.9999999999999818


A zero eigenvalue means that the determinant is 0, and that the system of equations Ax = b does not have a unique solution.

If the right-hand side is set to lambda\*x:

Ax = 0 means there are infinite solutions

Ax = b means there are infinite solutions if b is an image of A, 0 otherwise.

** an image of a vector is the result you have after a transformation to said vector

If a matrix has a complete set of eigenvectors and eigenvalues, then we can decompose it into:


A = Q /\ Q^-1


Q is a matrix where the column vectors are the eigenvectors.

/\ is a diagonal matrix with the eigenvalues.

In [22]:
print("A:\n", A)
Q = eigenvectors
Lambda = np.diag(eigenvalues)
Q_inv = la.inv(Q)
A2 = Q @ Lambda @ Q_inv
print("Reconstructed A2 (should match A):\n", np.real(A2))  # take real part to drop tiny imaginary residuals

A:
 [[ 3  2 -4]
 [ 1 -2  2]
 [-5  1  1]]
Reconstructed A2 (should match A):
 [[ 3.  2. -4.]
 [ 1. -2.  2.]
 [-5.  1.  1.]]


It can be thought of as a change of basis to eigenvector space!

## Positive Definite Matrices

A matrix is symmetric if its transpose is the same as itself.

In [23]:
A = np.array([[1, 2, 3],
              [2, 4, 2],
              [3, 2, 1]])
B = A.T
print("A:\n", A)
print("B (transpose of A):\n", B)
print("A == B:\n", A == B)

A:
 [[1 2 3]
 [2 4 2]
 [3 2 1]]
B (transpose of A):
 [[1 2 3]
 [2 4 2]
 [3 2 1]]
A == B:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


A symmetric matrix always has a complete set of real eigenvalues, and a set of eigenvectors that are mutually orthogonal (they are at right angles to one another).

A positive definite matrix is a symmetric matrix where all the eigenvalues are positive and not 0. If the eigenvalues are positive or 0, then the matrix is positive semi-definite.

Our previous example is not positive definite.

In [24]:
la.eig(A)[0]

array([ 6.82842712, -2.        ,  1.17157288])

Here is a positive definite matrix:

In [38]:
B = np.array([[ 2, -1,  0],
              [-1,  2, -1],
              [ 0, -1,  2]])
la.eig(B)[0]

array([3.41421356, 2.        , 0.58578644])

When working with real data, the covariance matrix is always positive definite.

## Assignment Section

**Question 1.**

Given the basis vectors `b1` and `b2` below, and the coordinate vector `coords = [4, -1]` (meaning $4\mathbf{b_1} - 1\mathbf{b_2}$), compute the following:

- `s`: the vector in standard coordinates produced by the linear combination $4b_1 - 1b_2$
- `is_independent`: a boolean — `True` if `b1` and `b2` are linearly independent, `False` otherwise. (Hint: check the rank of the matrix formed by stacking them as columns.)
- `coords_in_standard`: the coordinate vector of `s` expressed in the **standard** basis $\{[1,0], [0,1]\}$ — i.e., use `la.solve()` to find it

In [39]:
import numpy as np
from numpy import linalg as la

# Setting up the basis vectors b1 and b2
b1 = np.array([2, 1])
b2 = np.array([1, 3])

# Creating the linear combination vector
s = 4 * b1 - 1 * b2

# Checking if b1 and b2 are linearly independent by stacking the columns of b1 and b2 as a matrix and checking the rank
matrix = np.column_stack((b1, b2))
is_independent = la.matrix_rank(matrix) == 2

# Finding the coordinates in standard basis
coords_in_standard = la.solve(np.eye(2), s)

# Displaying the results
print(f"s = {s}")
print(f"b1 and b2 are linearly independent = {is_independent}")
print(f"Coordinate vector = {coords_in_standard}")

s = [7 1]
b1 and b2 are linearly independent = True
Coordinate vector = [7. 1.]


In [40]:
grader.check("q1")

q1 results: All test cases passed!

**Question 2.**
Given the matrix `A2` below, compute the following:

- `eigenvalues`: a numpy array of the eigenvalues of `A2`
- `det_from_eigs`: the determinant of `A2`
- `is_positive_definite`: a boolean — `True` if `A2` is positive definite (all eigenvalues real and positive), `False` otherwise


In [41]:
import numpy as np
from numpy import linalg as la

# Creating the matrix A2
A2 = np.array([[ 4, -2],
               [-2,  3]])

# Computing the eigenvalues
eigenvalues = la.eigvals(A2)

# Calculating the determinant from the eigenvalues
det_from_eigs = np.prod(eigenvalues)

# Checking if eigenvalues are real and positive / A2 is positive definite
is_positive_definite = np.all(eigenvalues > 0)

# Displaying the results
print(f"Eigenvalues = {eigenvalues}")
print(f"Determinant from eigenvalues = {det_from_eigs}")
print(f"A2 is positive definite = {is_positive_definite}")

Eigenvalues = [5.56155281 1.43844719]
Determinant from eigenvalues = 8.0
A2 is positive definite = True


In [42]:
grader.check("q2")

q2 results: All test cases passed!

**Question 3.**
Given matrix `A3` below, perform an eigendecomposition and use it to reconstruct the matrix. Then answer the following:

- `Q`: the matrix of eigenvectors (each column is an eigenvector)
- `Lambda`: the diagonal matrix of eigenvalues
- `A3_reconstructed`: the matrix reconstructed as $Q \cdot \Lambda \cdot Q^{-1}$
- `rank_A3`: the rank of `A3`

In [43]:
import numpy as np
from numpy import linalg as la

# creating the matrix A3
A3 = np.array([[ 3,  1,  0],
               [ 1,  3,  0],
               [ 0,  0,  2]])

## Computing the eigenvalues and eigenvectors
eigenvalues, eigenvectors = la.eig(A3)

# Creating the matrix of eigenvectors
Q = eigenvectors

# Creating the diagonal matrix of eigenvalues
Lambda = np.diag(eigenvalues)

# Recreating A3 as (Q Λ Q^(-1))
A3_reconstructed = Q @ Lambda @ la.inv(Q)

# Finding the rank of A3
rank_A3 = la.matrix_rank(A3)

# Displaying the results
print(f"Q = \n{Q}")
print(f"Lambda = \n{Lambda}")
print(f"A3 reconstructed = \n{A3_reconstructed}")
print(f"The rank of A3 = {rank_A3}")

Q = 
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Lambda = 
[[4. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
A3 reconstructed = 
[[3. 1. 0.]
 [1. 3. 0.]
 [0. 0. 2.]]
The rank of A3 = 3


In [44]:
grader.check("q3")

q3 results: All test cases passed!

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [45]:
grader.check_all()

q1 results: All test cases passed!

q2 results:
    q2 - 1 result:
        ❌ Test case failed
        Trying:
            assert np.allclose(eigenvalues, [5.56155281, 1.43844719])
        Expecting nothing
        **********************************************************************
        Line 1, in q2 0
        Failed example:
            assert np.allclose(eigenvalues, [5.56155281, 1.43844719])
        Exception raised:
            Traceback (most recent call last):
              File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.3312.0_x64__qbz5n2kfra8p0\Lib\doctest.py", line 1398, in __run
                exec(compile(example.source, filename, "single",
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             compileflags, True), test.globs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<doctest q2 0[0]>", line 1, in <module>
                assert np.allclose(eigenvalues, [5.56155